# Generated by Django 4.2.5 on 2023-09-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='images',
            new_name='imagem',
        ),
    ]
